# Generated by Django 4.2 on 2026-05-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incident', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyincident',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
